#!/bin/bash python3 

import os

# Assign wildcard sample names
configfile: "task_samples.yaml"

# Assign wildcard constraints
wildcard_constraints:
    sample='[a-zA-Z0-9]+'

rule all:
    input:         
        expand("08_cytosine_reports/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz.CpG_report.txt.gz", sample=config["samples"])

'''
# Need to add dirs
rule all:
    input:
        expand("{sample}_1.fq.gz_trimming_report.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.bam", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.bedGraph.gz", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz.CpG_report.merged_CpG_evidence.cov.gz", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz.CpG_report.txt.gz", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz.cytosine_context_summary.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.M-bias.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.nucleotide_stats.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.sorted.bam.histogram.pdf", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated.sorted.bam.insert.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplicated_splitting_report.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_pe.deduplication_report.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_PE_report.html", sample=config["samples"]),
        expand("{sample}_1_val_1_bismark_bt2_PE_report.txt", sample=config["samples"]),
        expand("{sample}_1_val_1_fastqc.html", sample=config["samples"]),
        expand("{sample}_1_val_1_fastqc.zip", sample=config["samples"]),
        expand("{sample}_1_val_1_screen.html", sample=config["samples"]),
        expand("{sample}_1_val_1_screen.txt", sample=config["samples"]),
        expand("{sample}_2.fq.gz_trimming_report.txt", sample=config["samples"]),
        expand("{sample}_2_val_2_fastqc.html", sample=config["samples"]),
        expand("{sample}_2_val_2_fastqc.zip", sample=config["samples"]),
        expand("{sample}_2_val_2_screen.html", sample=config["samples"]),
        expand("{sample}_2_val_2_screen.txt", sample=config["samples"]),
        expand("CpG_context_{sample}_1_val_1_bismark_bt2_pe.deduplicated.txt.gz", sample=config["samples"])
    
    
    
rule make_directories:
    message: "Making directories for data organization"
    output: 
        directory("00_time_logs/"),
        directory("00_std_err_logs/"),
        directory("02_trimmed/"),
        directory("03_screened/"),
        directory("04_aligned/"),
        directory("05_deduplicated/"),
        directory("06_sorted/"),
        directory("06_nt_coverage/"),
        directory("06_methylation/"),
        directory("07_size_metrics/"),
        directory("08_cytosine_reports")
    shell: """
    mkdir 00_time_logs
    mkdir 00_std_err_logs
    mkdir 02_trimmed
    mkdir 03_screened
    mkdir 04_aligned
    mkdir 05_deduplicated
    mkdir 06_sorted
    mkdir 06_nt_coverage
    mkdir 06_methylation
    mkdir 07_size_metrics
    mkdir 08_cytosine_reports
    """

rule trim:
    message: "Trimming samples"
    input:
        r1 = "01_raw_sequences/{sample}_1.fq.gz",
        r2 = "01_raw_sequences/{sample}_2.fq.gz",
        make_dirs = directory("00_time_logs/")
    output:
        out1 = "02_trimmed/{sample}_1.fq.gz_trimming_report.txt",
        out2 = "02_trimmed/{sample}_1_val_1_fastqc.html",
        out3 = "02_trimmed/{sample}_1_val_1_fastqc.zip",
        out4 = "02_trimmed/{sample}_1_val_1.fq.gz",
        out5 = "02_trimmed/{sample}_2.fq.gz_trimming_report.txt",
        out6 = "02_trimmed/{sample}_2_val_2_fastqc.html",
        out7 = "02_trimmed/{sample}_2_val_2_fastqc.zip",
        out8 = "02_trimmed/{sample}_2_val_2.fq.gz"
    log: "00_std_err_logs/02_trimmed_{sample}.log"
    benchmark: "00_time_logs/02_trimmed_{sample}.txt"
    threads: 1
    resources: # https://snakemake.readthedocs.io/en/stable/executing/cluster.html
        mem_mb: 10000, # 10 gb memory
    shell: "trim_galore --paired --cores {threads} --2colour 20 --fastqc --clip_r1 10 --clip_r2 20 --three_prime_clip_r1 10 --three_prime_clip_r2 10 --output_dir 02_trimmed/ {input.r1} {input.r2} 2> {log}"

rule screen:
    message: "Screening samples for sample origin"
    input:
        conf = "00_software/fastq_screen.conf",
        r1 = "02_trimmed/{sample}_1_val_1.fq.gz",
        r2 = "02_trimmed/{sample}_2_val_2.fq.gz"
    output: 
        out1 = "03_screened/{sample}_1_val_1_screen.bisulfite_orientation.png",
        out2 = "03_screened/{sample}_1_val_1_screen.html",
        out3 = "03_screened/{sample}_1_val_1_screen.png",
        out4 = "03_screened/{sample}_1_val_1_screen.txt"
    log: "00_std_err_logs/03_screened_{sample}.log"
    benchmark: "00_time_logs/03_screened_{sample}.txt"
    shell: """
    fastq_screen --conf {input.conf} --bisulfite {input.r1} {input.r1} > 03_screened/ 2> {log}
    """ 
  
rule align:
    message: "Aligning bisfulite reads"
    input:
        r1 = "02_trimmed/{sample}_1_val_1.fq.gz",
        r2 = "02_trimmed/{sample}_2_val_2.fq.gz"
    output: 
        out1 = "04_aligned/{sample}_1_val_1_bismark_bt2_pe.bam",
        out2 = "04_aligned/{sample}_1_val_1_bismark_bt2_PE_report.txt"
    log: "00_std_err_logs/04_aligned_{sample}.txt"
    benchmark: "00_time_logs/04_aligned_{sample}.txt"
    shell: """
    bismark -n 1 --genome /share/lasallelab/genomes/{config[genome]}/ --multicore 6 -1 {input.r1} -2 {input.r2} 2> {log}
    mv {wildcards.sample}_1_val_1_bismark_bt2_pe.bam 04_aligned/
    mv {wildcards.sample}_1_val_1_bismark_bt2_PE_report.txt 04_aligned/
    """

rule deduplicate:
    message: "Removing PCR duplicates"
    input: "04_aligned/{sample}_1_val_1_bismark_bt2_pe.bam"
    output:
        "05_deduplicated/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bam",
        "05_deduplicated/{sample}_1_val_1_bismark_bt2_pe.deduplication_report.txt"
    log: "00_std_err_logs/05_deduplicated_{sample}.txt"
    benchmark: "00_time_logs/05_deduplicated_{sample}.txt"
    shell: """
    deduplicate_bismark --bam --paired {input} 2> {log}
    mv {wildcards.sample}_1_val_1_bismark_bt2_pe.deduplicated.bam 05_deduplicated/
    mv {wildcards.sample}_1_val_1_bismark_bt2_pe.deduplication_report.txt 05_deduplicated/
    """
 
rule sort:
    message: "Sorting BAM files"
    input: "05_deduplicated/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bam"
    output: "06_sorted/{sample}_1_val_1_bismark_bt2_pe.deduplicated.sorted.bam"
    log: "00_std_err_logs/06_sorted_{sample}.txt"
    benchmark: "00_time_logs/06_sorted_{sample}.txt"
    shell: "picard SortSam INPUT={input} OUTPUT={output} SORT_ORDER=coordinate 2> {log}"

rule size_metrics:
    message: "Collecting insert size metrics"
    input: "06_sorted/{sample}_1_val_1_bismark_bt2_pe.deduplicated.sorted.bam"
    output: 
        ins = "07_size_metrics/{sample}_1_val_1_bismark_bt2_pe.deduplicated.sorted.bam.insert.txt",
        hist = "07_size_metrics/{sample}_1_val_1_bismark_bt2_pe.deduplicated.sorted.bam.histogram.pdf"
    log: "00_std_err_logs/07_size_metrics_{sample}.txt"
    benchmark: "00_time_logs/07_size_metrics_{sample}.txt"
    shell: "picard CollectInsertSizeMetrics INPUT={input} OUTPUT={output.ins} HISTOGRAM_FILE={output.hist} ASSUME_SORTED=TRUE 2> {log}"

rule nucleotide_coverage:
    message: "Assessing nucleotide coverage"
    input: "05_deduplicated/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bam"
    output: "06_nt_coverage/{sample}_1_val_1_bismark_bt2_pe.deduplicated.nucleotide_stats.txt"
    log: "00_std_err_logs/06_nt_coverage_{sample}.txt"
    benchmark: "00_time_logs/06_nt_coverage_{sample}.txt"
    shell: """
    bam2nuc --genome_folder /share/lasallelab/genomes/{config[genome]}/ {input} > {output} 2> {log}
    touch dummy_{wildcards.sample}.txt
    """
    
'''   
rule extract_methylation:
    message: "Extracting methylation"
    input: "05_deduplicated/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bam"
    output: 
        "06_methylation/CpG_context_{sample}_1_val_1_bismark_bt2_pe.deduplicated.txt.gz",
        "06_methylation/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bedGraph.gz",
        "06_methylation/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz",
        "06_methylation/{sample}_1_val_1_bismark_bt2_pe.deduplicated.M-bias_R1.png",
        "06_methylation/{sample}_1_val_1_bismark_bt2_pe.deduplicated.M-bias_R2.png",
        "06_methylation/{sample}_1_val_1_bismark_bt2_pe.deduplicated.M-bias.txt",
        "06_methylation/{sample}_1_val_1_bismark_bt2_pe.deduplicated_splitting_report.txt",
        "06_methylation/Non_CpG_context_{sample}_1_val_1_bismark_bt2_pe.deduplicated.txt.gz"
    log: "00_std_err_logs/06_methylation_{sample}.txt"
    benchmark: "00_time_logs/06_methylation_{sample}.txt"
    shell: "bismark_methylation_extractor --paired-end --gzip --comprehensive --merge_non_CpG --bedGraph --multicore 6 --buffer_size 34G {input} --output_dir 06_methylation/ 2> {log}"

rule cytosine_reports:
    message: "Generating genome-wide cytosine reports"
    input:
        "06_methylation/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz"
    output: 
        "08_cytosine_reports/{sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz.CpG_report.txt.gz"
    log: "00_std_err_logs/08_cytosine_reports_{sample}.txt"
    benchmark: "00_time_logs/08_cytosine_reports_{sample}.txt"
    shell: "coverage2cytosine --dir 08_cytosine_reports --gzip --merge_CpG {input} --genome_folder /share/lasallelab/genomes/{config[genome]}/ --output {wildcards.sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz.CpG_report.txt.gz 2> {log}"
    
'''  
rule qc_report:
    message: "Generating Bismark QC reports"
    input:
    output:
    log:
    benchmark:
    shell: "bismark2report --output {output.out_file} --dir {output.out_dir}2> {log}"
'''