#!/bin/bash python3 

import os

# Assign wildcard sample names
configfile: "task_samples.yaml"

# Assign wildcard constraints
wildcard_constraints:
    sample='[a-zA-Z0-9]+'

rule all:
    input: 
        expand("dummy_{sample}.txt", sample=config["samples"])

rule trim:
    message: "Trimming samples"
    input:
        r1 = "01_raw_sequences/{sample}_1.fq.gz",
        r2 = "01_raw_sequences/{sample}_2.fq.gz"
    output:
        dummy = "dummy_{sample}.txt"
    log: "00_std_err_logs/02_trimmed_{sample}.log"
    benchmark: "00_time_logs/02_trimmed_{sample}.txt"
    threads: 1
    shell: """
    trim_galore --paired --cores {threads} --2colour 20 --fastqc --clip_r1 10 --clip_r2 20 --three_prime_clip_r1 10 --three_prime_clip_r2 10 --output_dir 02_trimmed/ {input.r1} {input.r2}
    touch {output.dummy}
    """

'''
rule screen:
    message: "Screening samples for sample origin"
    input:
        conf = "00_software/fastq_screen.conf"
        r1 = "02_trimmed/{sample}_1_val_1.fq.gz",
        r2 = "02_trimmed/{sample}_2_val_2.fq.gz"
    output:
    shell: "fastq_screen --conf {input.conf} --bisulfite {input.r1} {input.r1}" 
    
rule align:
    message: "Align bisfulite reads"
    input:
        r1 = "02_trimmed/{sample}_1_val_1.fq.gz",
        r2 = "02_trimmed/{sample}_2_val_2.fq.gz"
    output:
    shell: "bismark -n 1 --genome /share/lasallelab/genomes/{wildcards.genome}/ --multicore 6 -1 {input.r1} -2 {input.r2}"
    
rule deduplicate:
    message: "Removing PCR duplicates"
    input:
    output:
    shell: "deduplicate_bismark --bam --paired ${BAM}"
'''

# Insert Size Metrics

# Nucleotide Coverage

# Extract Methylation

# Cytosine and QC Reports