cluster:
  mkdir -p logs/{rule}/ &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=epigenerator-{rule}
    --ntasks={resources.nodes}
    --nodes={resources.nodes}
    --output=logs/{rule}/{jobid}.out
    --error=logs/{rule}/{jobid}.err
    --partition={resources.partition}
    --account={resources.account}
    --parsable
default-resources:
  - mem_mb=2000
  - time=60
  - account=lasallegrp
  - partition=high
  - threads=1
  - nodes=1
jobs: 50
latency-wait: 60
local-cores: 1
restart-times: 1
max-jobs-per-second: 100
max-status-checks-per-second: 20
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-prefix: /quobyte/lasallegrp/programs/.conda/
conda-frontend: conda
cluster-status: 00_slurm/slurm-status.py
